# Generated by Django 3.2.15 on 2023-03-23 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_bookings_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name_plural': 'Booking Management'},
        ),
        migrations.AlterModelOptions(
            name='integrals',
            options={'verbose_name_plural': 'Credit Management'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name_plural': 'Room Management'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Student Management'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name_plural': 'Management Tips'},
        ),
        migrations.AlterField(
            model_name='bookings',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activate Status'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Reserved Seat Number'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='period',
            field=models.IntegerField(choices=[(1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')], default=1, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.rooms', verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.students', verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='integrals',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='integrals',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activate Status'),
        ),
        migrations.AlterField(
            model_name='integrals',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.students', verbose_name='Students'),
        ),
        migrations.AlterField(
            model_name='integrals',
            name='text',
            field=models.TextField(default='', max_length=220, verbose_name='Warning Content'),
        ),
        migrations.AlterField(
            model_name='integrals',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='integrals',
            name='title',
            field=models.CharField(default='', max_length=220, verbose_name='Warning Title'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activate Status'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='name',
            field=models.CharField(default='', max_length=22, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='number',
            field=models.IntegerField(default=0, verbose_name='The number of seats'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='photo',
            field=models.FileField(default='', upload_to='Room/photo/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(default='', max_length=22, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='students',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Study motivation'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(default='', max_length=22, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(default='', max_length=32, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(default='', max_length=11, verbose_name='Student_ID'),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.FileField(default='', upload_to='Students/photo/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='students',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='text',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='text',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activate Status'),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='text',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(default='', max_length=120, verbose_name='Title'),
        ),
    ]
